### ISSUE TITLE
Bad provider information in sample project

### ISSUE THREAD

**Issue by daniel-dnil** [15knots/cmake4eclipse-sample-projects#1]
**This is a...**  

- [X] Bug Report  
- [ ] Enhancement Request

Setup
=====
eclipse.buildId=4.10.0.I20181206-0815
CDT: 9.6.0.201812111211
cmake4eclipse: 1.13.0.201901031836
OS: Linux Mint 19
cmake version 3.10.2

Common Prepare
==============
git clone https://github.com/daniel-dnil/cm4e-tc.git && cd cm4e-tc

TC1: Bad provider information in sample project
==========================================
1) git checkout 7662d205

2) Import project C-1src from folder proj-cn into empty new WS, this is a copy from
   the cmake4eclipse-sample-projects repo.

3) Project will autobuild OK

4) Indexer runs after build, but fails to find any compiler built-in include paths (can't find stdio.h etc).
   C/C++ General->Preprocessor Include Paths, Macros etc.->Providers only contains
   "CMAKE_EXPORT_COMPILE_COMMANDS Parser". No "Includes" folder is shown in Eclipse project structure.

5) Close and re-open project

6) "Includes" folder is shown only after project close->reopen. Is this a CDT bug?

7) Add the "CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins" provider. Now the compiler built-in paths are found
   and the indexer runs OK. Commit this change to git, SHA 6c5a8c8. Now we have a state where the project can be
   built and open closed. Maybe CMAKE_EXPORT_COMPILE_COMMANDS Compiler Built-ins should be part of sample project?

**Comment by 15knots** [comment]
Fixed in 648963ce8ed79b26c56aba1786b07d0a53792172
